---
# This playbook contains some basic setup steps that should be run on all nodes.

- name: create /etc/resolv.conf
  template: src=resolv.conf.j2 dest=/etc/resolv.conf
  tags: common

- name: common should only use IPv4
  lineinfile:
    path: /etc/yum.conf
    line: 'ip_resolve=4'
  tags: common

- name: Enable epel repo
  yum: name=epel-release state=present
  tags: common

- name: upgrade all packages
  yum: name=* state=latest
  notify: reboot server
  tags: common

- name: wait for container to reboot
  become: false
  wait_for: port=22 host="{{ansible_host}}" search_regex=OpenSSH delay=10
  connection: local
