---
# This playbook contains some basic setup steps that should be run on all nodes.

- name: create /etc/resolv.conf
  template: src=resolv.conf.j2 dest=/etc/resolv.conf

- name: Yum should only use IPv4
  lineinfile:
    path: /etc/yum.conf
    line: 'ip_resolve=4'
  tags: yum

- name: Enable epel repo
  yum: name=epel-release state=present
  tags: yum
